version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
  test:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    command: ["npm", "run", "test"]

